config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "home#index" 
  match 'calendar/:day/:type', controller: :calendar, action: :menu, via: :get, as: 'daily_menu'
  match 'calendar', controller: :calendar, action: :index, via: [:get], as: 'calendar'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  telegram_webhook TelegramWebhooksController

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :registerable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable,
	 :confirmable, :trackable, :timeoutable, :lockable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  enum menu_type: [:puree, :solid]

  validates_presence_of :date
  validates_presence_of :menu_type
  validates_uniqueness_of :menu_type, scope: :date
  validates_presence_of :description

  rails_admin do
    list do
      field :date
      field :menu_type
    end
    show do
      field :date
      field :menu_type
      field :description
    end
    edit do
      field :date
      field :menu_type
      field :description
    end
  end

  # Wrappers for simple_calendar
  def start_time
    self.date
  end
  def end_time
    self.date
  end
end

app/models/notice.rb
class Notice < ApplicationRecord

  rails_admin do
    list do
      field :message
      field :sent
    end
    show do
      field :message
      field :sent
    end
    edit do
      field :message
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    @menus = Menu.all
  end

  def menu
    @menu = Menu.find_by_date_and_menu_type params[:day], params[:type]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def calendar
    @menus = Menu.all
  end

  def menu 
  end
end

app/controllers/telegram_webhooks_controller.rb
class TelegramWebhooksController < Telegram::Bot::UpdatesController
  include Telegram::Bot::UpdatesController::MessageContext
  before_action :get_telegram_client, :set_locale

  def start!(*)
    respond_with :message, text: t('.content', first_name: from['first_name'])
  end

  def help!(*)
    respond_with :message, text: t('.content')
  end

  def memo!(*args)
    if args.any?
      session[:memo] = args.join(' ')
      respond_with :message, text: t('.notice')
    else
      respond_with :message, text: t('.prompt')
      save_context :memo!
    end
  end

  def remind_me!(*)
    to_remind = session.delete(:memo)
    reply = to_remind || t('.nothing')
    respond_with :message, text: reply
  end

  def keyboard!(value = nil, *)
    puts "**** Recibimos #{value} del teclado"
    case value
    when "Today", "Hoy"
      menus = Menu.where(date: Date.today)
      if menus.any?
        text = t("messages.today_menu_is") + ":\n"
        menus.each do |menu|
          text += menu.menu_type + " -> " + menu.description + "\n"
        end
      else
        text = t("messages.no_menu_for_day", l(Date.today)) + ": "
      end
      respond_with :message, text: text
    when "Tomorrow", "Mañana"
      menus = Menu.where(date: Date.today + 1.day)
      if menus.any?
        text = t("messages.tomorrow_menu_is") + ":\n"
        menus.each do |menu|
          text += menu.menu_type + " -> " + menu.description + "\n"
        end
      else
        text = t("messages.no_menu_for_day", l(Date.today)) + ": "
      end
      respond_with :message, text: text
    else
      save_context :keyboard!
      respond_with :message, text: t('.prompt'), reply_markup: {
        keyboard: [t('.buttons')],
        resize_keyboard: true,
        one_time_keyboard: true,
        selective: true,
      }
    end
  end

  def inline_keyboard!(*)
    respond_with :message, text: t('.prompt'), reply_markup: {
      inline_keyboard: [
        [
          {text: t('.alert'), callback_data: 'alert'},
          {text: t('.no_alert'), callback_data: 'no_alert'},
        ],
        [{text: t('.repo'), url: 'https://github.com/sramos/elolivar-bot'}],
      ],
    }
  end

  def callback_query(data)
    if data == 'alert'
      answer_callback_query t('.alert'), show_alert: true
    else
      answer_callback_query t('.no_alert')
    end
  end

  def message(message)
    respond_with :message, text: t('.content', text: message['text'])
  end

  def inline_query(query, _offset)
    query = query.first(10) # it's just an example, don't use large queries.
    t_description = t('.description')
    t_content = t('.content')
    results = Array.new(5) do |i|
      {
        type: :article,
        title: "#{query}-#{i}",
        id: "#{query}-#{i}",
        description: "#{t_description} #{i}",
        input_message_content: {
          message_text: "#{t_content} #{i}",
        },
      }
    end
    answer_inline_query results
  end

  # As there is no chat id in such requests, we can not respond instantly.
  # So we just save the result_id, and it's available then with `/last_chosen_inline_result`.
  def chosen_inline_result(result_id, _query)
    session[:last_chosen_inline_result] = result_id
  end

  def last_chosen_inline_result!(*)
    result_id = session[:last_chosen_inline_result]
    if result_id
      respond_with :message, text: t('.selected', result_id: result_id)
    else
      respond_with :message, text: t('.prompt')
    end
  end

  def action_missing(action, *_args)
    if action_type == :command
      respond_with :message,
        text: t('telegram_webhooks.action_missing.command', command: action_options[:command])
    else
      respond_with :message, text: t('telegram_webhooks.action_missing.feature', action: action)
    end
  end

  def get_telegram_client
    @telegram_client = Client.find_or_create_by telegram_id: from['id']
    @telegram_client.update_attributes username: from['username'],
                                       first_name: from['first_name'],
                                       is_bot: from['is_bot'],
                                       updated_at: Time.now
  end

  def set_locale
    I18n.locale = from['language_code'] || I18n.default_locale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendar/index.html.erb
<%= month_calendar events: @menus do |date, menus| %>
  <%= date %>

  <% menus.each do |menu| %>
    <div>
      <%= link_to menu.menu_type, daily_menu_path(type: menu.menu_type, day: menu.date) %>
    </div>
  <% end %>
<% end %>

app/views/calendar/menu.html.erb
<%= @menu.description %>

app/views/home/index.html.erb
<img src="<%= image_url('sestrjevitovschii-ina-7zfQ6sbWVyE-unsplash.jpg') %>" width="100%">

<center>
<a style="background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system, BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto, Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px" href="https://unsplash.com/@inasestrjevitovschii?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge" target="_blank" rel="noopener noreferrer" title="Download free do whatever you want high-resolution photos from Sestrjevitovschii Ina"><span style="display:inline-block;padding:2px 3px"><svg xmlns="http://www.w3.org/2000/svg" style="height:12px;width:auto;position:relative;vertical-align:middle;top:-2px;fill:white" viewBox="0 0 32 32"><title>unsplash-logo</title><path d="M10 9V0h12v9H10zm12 5h10v18H0V14h10v9h12v-9z"></path></svg></span><span style="display:inline-block;padding:2px 3px">Sestrjevitovschii Ina</span></a>
</center> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TelegramBotApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="yield">
      <%= yield %>
    </div>
  </body>
</html>